[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[project]
name = "rust_bm25"
requires-python = ">=3.13"
dynamic = ["version"]

[tool.maturin]
features = ["pyo3/extension-module"]
